### ISSUE TITLE
examples or reference to tutorials pls!

### ISSUE THREAD

**Issue by popaaaandrei** [rxwei/CCUDA#1]
Hello Richard,

👍👍👍👍 for making this available.
Please when you have the time maybe you can add some examples or references regarding applying NVIDIA libs with Swift?

Thank you,
Andrei

**Comment by rxwei** [comment]
Sure. Currently I'm working on a pure Swift wrapper for this:
https://github.com/rxwei/cuda-swift

Once that's done I'll write a tutorial :)

**Comment by popaaaandrei** [comment]
Thank you sir, you are a pioneer :D 🎱

**Comment by rxwei** [comment]
You may now find some informative description here at [cuda-swift](https://github.com/rxwei/cuda-swift)
